---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka,http://localhost:8012/eureka,http://localhost:8013/eureka
---
spring:
  profiles: subject
  application:
    name: subject
  
---
spring:
  profiles: verb
  application:
    name: verb

---
spring:
  profiles: article
  application:
    name: article

---
spring:
  profiles: adjective
  application:
    name: adjective

---
spring:
  profiles: noun
  application:
    name: noun

---
spring:
  profiles: cold-noun
  application:
    name: noun      
